### ISSUE TITLE
Particle Identifier

### ISSUE THREAD

**Issue by Leimeroth** [ovito-org/DistancesAndAnglesOverlay#1]
Particle Identifier is not always are particle property, leading to errors f.e. when opening a h5 file instead of a lammps dump. Can be fixed f.e. by using the compute property modifier to set "Particle Identifier" to ParticleIndex+1.

**Comment by nnn911** [comment]
Thanks for the suggested workaround. Starting from version 2023.1 (bcc669f) the overlay will automatically use particle indices if no _particle identifiers_ are present in the data collection. Note, this release requires the upcoming OVITO Pro 3.9.3.
